Explicit `CachedFuzzySearchable<T>` wrapper
viktorasl/FuzzySearch pull request #3
Opened 2017-05-29 20:05 UTC by LuizZak

As discussed in #2, this is an explicit structure that wraps over an existing, non-cacheable `FuzzySearchable`, providing a thin layer that allows for caching of the tokenized searchable string.

This version has a few advantages that I'm planning on checking and proving related to resilience against sharing cache across multiple value-type `FuzzySearchable` implementers, since the implementer is copied into a private, constant field within the `CachedFuzzySearchable<T>` wrapper.

2017-05-30 06:14 UTC, viktorasl commented
Everything looks great! Let me know which PR you prefer.

2017-05-30 17:14 UTC, LuizZak commented
@viktorasl Cool! I think this seems like the preferred cleaner way of dealing with caching, it's decoupled from the base protocol and allows for discarding of caching, in case it's heavyweight to keep around.

You can merge this version in!

2017-05-30 18:11 UTC, viktorasl commented
Could you take a look to those 2 comments?

2017-05-30 19:19 UTC, LuizZak commented
Sorry, can't seem to find them, where?

2017-05-30 19:28 UTC, viktorasl requested changes

2017-05-30 19:28 UTC, viktorasl commented on Source/FuzzySearch.swift
> +    func fuzzyTokenized() -> FuzzyTokens
I think `fuzzyTokenized` method could be private/internal unless we would like it to be overridable.

2017-05-30 19:28 UTC, viktorasl commented on Tests/FuzzySearchTests.swift
> +            _ = spanishWordsCached.fuzzyMatch("la sart")
Fuzzy searching whole "la sart" won't show better performance right away, because it will tokenize each word only once, what you should do is:
```swift
measure {
            _ = spanishWordsCached.fuzzyMatch("l")
            _ = spanishWordsCached.fuzzyMatch("la")
            _ = spanishWordsCached.fuzzyMatch("la ")
            _ = spanishWordsCached.fuzzyMatch("la s")
            _ = spanishWordsCached.fuzzyMatch("la sa")
            _ = spanishWordsCached.fuzzyMatch("la sar")
            _ = spanishWordsCached.fuzzyMatch("la sart")
 }
```
something like that. Change the implementation in `testSpeedOfFuzzySearchFor1000SpanishWords` as well.

2017-05-30 19:29 UTC, viktorasl commented
Sorry, didn't see that I didn't submit review and it was pending

2017-05-30 20:07 UTC, LuizZak commented
Addressed review, I've had to be slightly creative with the public/private protocol implementations to hide away `fuzzyTokenized` and still make it transparently available to `CachedFuzzySearchable.fuzzyMatch`. More info is available in a comment down at that method's implementation.

2017-06-04 07:17 UTC, viktorasl approved these changes

2017-06-04 07:17 UTC, merged